blueprint:
  name: Alarm actionable notifications when entering a zone for Android
  description: >
    Send actionable notifications to an Android device when an entity enters a zone.
    Supports Alarmo conditions.
  domain: automation
  input:
    notify_device:
      name: Device to notify
      selector:
        device:
          integration: mobile_app

    trigger_entity:
      name: Trigger entity
      selector:
        entity:
          domain: person

    trigger_event:
      name: Trigger Event
      selector:
        select:
          options:
            - leave
            - enter

    trigger_zone:
      name: Trigger Zone
      selector:
        entity:
          domain: zone

    first_condition:
      name: Alarmo Condition
      selector:
        select:
          options:
            - is_disarmed
            - is_armed_away

    notification_title:
      name: Notification title
      default: ''

    notification_message:
      name: Notification message
      default: ''

    persistent_notification:
      name: Create persistent notification?
      selector:
        boolean: {}
      default: false

    action_1_title:
      name: First action name
      default: ''
    action_1_uri:
      name: URI for action 1
      default: ''
    first_action:
      name: Action 1
      default: []
      selector:
        action: {}

    action_2_title:
      name: Second action name
      default: ''
    action_2_uri:
      name: URI for action 1
      default: ''
    second_action:
      name: Action 2
      default: []
      selector:
        action: {}

    action_3_title:
      name: Third action name
      default: ''
    action_3_uri:
      name: URI for action 3
      default: ''
    third_action:
      name: Action 3
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

variables:
  notify_device: !input notify_device
  trigger_entity: !input trigger_entity
  trigger_event: !input trigger_event
  trigger_zone: !input trigger_zone
  first_condition: !input first_condition
  notification_title: !input notification_title
  notification_message: !input notification_message
  persistent_notification: !input persistent_notification
  action_1_title: !input action_1_title
  action_1_uri: !input action_1_uri
  first_action: !input first_action
  action_2_title: !input action_2_title
  action_2_uri: !input action_2_uri
  second_action: !input second_action
  action_3_title: !input action_3_title
  action_3_uri: !input action_3_uri
  third_action: !input third_action

trigger:
  - platform: zone
    entity_id: !input trigger_entity
    zone: !input trigger_zone
    event: !input trigger_event

condition:
  - condition: device
    device_id: 7abd75f2dc3a770df4849d03a0e2ff97
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarmo
    type: !input first_condition

action:
  - domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: "{{ notification_title }}"
    message: "{{ notification_message }}"
    data:
      persistent: {{ persistent_notification }}
      tag: "{{ notification_title }}"
      actions: >
        {% set out = [] %}
        {% set titles = [action_1_title, action_2_title, action_3_title] %}
        {% set uris   = [action_1_uri,   action_2_uri,   action_3_uri] %}

        {% for t in titles %}
          {% if t|length > 0 %}
            {% set i = loop.index - 1 %}
            {% set act = {
              "action": ("URI" if uris[i]|length > 0 else "action" ~ (i+1)),
              "title": t
            } %}
            {% if uris[i]|length > 0 %}
              {% set act = act | combine({"uri": uris[i]}) %}
            {% endif %}
            {% set out = out + [act] %}
          {% endif %}
        {% endfor %}
        {{ out }}

  - wait_for_trigger:
      platform: event
      event_type: mobile_app_notification_action

  - choose:
      - conditions: "{{ wait.trigger.event.data.action == 'action1' }}"
        sequence: !input first_action
      - conditions: "{{ wait.trigger.event.data.action == 'action2' }}"
        sequence: !input second_action
      - conditions: "{{ wait.trigger.event.data.action == 'action3' }}"
        sequence: !input third_action
